apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeproject
  template:
    metadata:
      labels:
        app: nodeproject
    spec:
      containers:
        - name: app
          image: varshakamble/nodeproject:v2
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
